In [74]:
# import dependencies
import pandas as pd
import numerapi
import sklearn.linear_model
from catboost import CatBoostClassifier
from catboost import CatBoostRegressor,  Pool
from tqdm import tqdm
import lightgbm
import numpy as np
from xgboost import XGBRegressor
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import tensorflow_probability as tfp
import matplotlib.pyplot as plt
import math
from skimage.transform import resize
from skimage.io import imsave
from skimage.io import imread

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
# download the latest training dataset (takes around 30s)
training_data = pd.read_csv("train_data-kaz-10.csv")
# training_data = pd.read_csv("https://numerai-public-datasets.s3-us-west-2.amazonaws.com/latest_numerai_training_data.csv.xz")
del training_data['Unnamed: 0']
training_data.head()

,0,1,2,3,4,5,6,7,8,9,...,42,43,44,45,46,47,48,49,target,era
0,0.625115,0.446158,0.531525,0.335567,0.405357,0.518093,0.474484,0.491956,0.533080,0.486160,...,0.370507,0.552685,0.304854,0.200940,0.481556,0.530445,0.458085,0.519534,0.50,era1
1,0.367690,0.602062,0.500317,0.540271,0.287590,0.489212,0.525986,0.669204,0.377609,0.361885,...,0.267438,0.493574,0.297666,0.407217,0.533826,0.673376,0.336869,0.467933,0.25,era1
2,0.675877,0.360629,0.376649,0.329879,0.526551,0.417776,0.485493,0.662721,0.333822,0.394766,...,0.579851,0.511115,0.387974,0.571073,0.461804,0.673221,0.186182,0.436037,0.25,era1
3,0.644683,0.497132,0.577763,0.658211,0.315884,0.563425,0.812878,0.532486,0.278397,0.444438,...,0.383529,0.600189,0.432368,0.386079,0.595988,0.669761,0.265909,0.360806,0.25,era1
4,0.255260,0.368295,0.403755,0.496896,0.238508,0.562416,0.486466,0.474467,0.118016,0.508690,...,0.605335,0.573041,0.607115,0.321210,0.479349,0.574421,0.481902,0.723485,0.75,era1

In [3]:
# download the latest tournament dataset (takes around 30s)
tournament_data = pd.read_csv("tournament_data-kaz-10.csv")
# tournament_data = pd.read_csv("https://numerai-public-datasets.s3-us-west-2.amazonaws.com/latest_numerai_tournament_data.csv.xz")
del tournament_data['Unnamed: 0']
tournament_data.head()

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,target,era,type,id
0,0.684969,0.537315,0.644790,0.475414,0.522303,0.561284,0.441950,0.583328,0.357338,0.583919,...,0.652358,0.747293,0.560961,0.417274,0.602620,0.593732,0.25,era121,validation,n0003aa52cab36c2
1,0.462252,0.545916,0.394655,0.378866,0.569654,0.708049,0.495076,0.426700,0.565530,0.217472,...,0.594471,0.464464,0.739603,0.395773,0.587933,0.522045,0.50,era121,validation,n000920ed083903f
2,0.582050,0.557493,0.535555,0.323159,0.506384,0.605278,0.365147,0.181733,0.332626,0.691691,...,0.639979,0.540645,0.414977,0.393736,0.625929,0.519788,1.00,era121,validation,n0038e640522c4a6
3,0.419429,0.462896,0.448324,0.513063,0.390499,0.412967,0.390469,0.337310,0.549885,0.500408,...,0.414323,0.467435,0.382670,0.339632,0.606715,0.264071,0.50,era121,validation,n004ac94a87dc54b
4,0.632081,0.405627,0.395501,0.304732,0.428091,0.342243,0.480964,0.703205,0.334977,0.623257,...,0.541503,0.377432,0.390525,0.393758,0.299309,0.440200,0.75,era121,validation,n0052fe97ea0c05f

In [4]:
feature_cols = tournament_data.columns[[x for x in range(50)]]
feature_cols

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49'],
      dtype='object')

In [64]:
class Enviroment:
    
    def __init__(self, data, features):
        # len_obs_space = totalFeatures + 50 forward correlation
        self.extrafeatures = 5
        self.len_obs_space = len(features) +  self.extrafeatures 
        self.observation_space_high = np.array([1 for x in range(self.len_obs_space)])
        self.observation_space_low = np.array([0 for x in range(self.len_obs_space)])
        # cada accion seran en steps de 0.01
        self.n_action = 10

In [83]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Activation, Flatten
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.optimizers import Adam
class DQNAgent:
    def __init__(self):
        self.model = self.create_model()
    def create_model(self):
        model = Sequential()

        model.add(Conv2D(256, (3, 3), input_shape=env.OBSERVATION_SPACE_VALUES))  # OBSERVATION_SPACE_VALUES = (10, 10, 3) a 10x10 RGB image.
        model.add(Activation('relu'))
        model.add(MaxPooling2D(pool_size=(2, 2)))
        model.add(Dropout(0.2))

        model.add(Conv2D(256, (3, 3)))
        model.add(Activation('relu'))
        model.add(MaxPooling2D(pool_size=(2, 2)))
        model.add(Dropout(0.2))

        model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
        model.add(Dense(64))

        model.add(Dense(env.ACTION_SPACE_SIZE, activation='linear'))  # ACTION_SPACE_SIZE = how many choices (9)
        model.compile(loss="mse", optimizer=Adam(lr=0.001), metrics=['accuracy'])
        return model